// THIS FILE IS AUTO GENERATED
import { IconTree, IconType } from '../lib/cjs';
export declare const BrandBerdikarier: IconType;
export declare const BrandBerdikarierBOld: IconType;
export declare const BrandBerdikarierB: IconType;
export declare const BrandIlkhoeri: IconType;
export declare const BrandCSS3: IconType;
export declare const BrandChakraUI: IconType;
export declare const BrandDiscord: IconType;
export declare const BrandGMail: IconType;
export declare const BrandGoogle: IconType;
export declare const BrandGithub: IconType;
export declare const BrandGithubIOcticon: IconType;
export declare const BrandHTML5: IconType;
export declare const BrandInstagram: IconType;
export declare const BrandLinkedIn: IconType;
export declare const BrandMantine: IconType;
export declare const BrandNextJS: IconType;
export declare const BrandReact: IconType;
export declare const BrandTailwind: IconType;
export declare const BrandTwitter: IconType;
export declare const Chain: IconType;
export declare const KiosSquare: IconType;
export declare const SquareArrow: IconType;
export declare const BrandIoeri: IconType;
